[workspace]
members = ["cirond", "cironctl", "ciron-common"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Zaptoss","SCTG Dev Team"]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.104"
config = "0.15.26"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive"] }
shell-words = "1.1"

# gRPC dependencies
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
prost = "0.14.4"
prost-types = "0.14.4"
